### ISSUE TITLE
python

### ISSUE THREAD

**Issue by shui-tian-ju-shi** [LightDXY/ICT_DeepFake#2]
Can you tell me What version of Python are you using.    2.7?

**Comment by LightDXY** [comment]
hi, we use python 3.6 by default

**Comment by shui-tian-ju-shi** [comment]
Thanks for your reply very much!

**Comment by shui-tian-ju-shi** [comment]
I havn't install conda .so I run your command "bash setup.sh"under virtualenv enviroment.but I met this error.could you help me ?
![image](https://user-images.githubusercontent.com/95734189/165045599-a2db84bc-6f5b-48be-889d-3223d63640ef.png)

**Comment by shui-tian-ju-shi** [comment]
I use pip to install the package in setup.py by myself ,with"--user" deleted,and the package installed sucesssfully.I hope it won't raise error .haha.

**Comment by LightDXY** [comment]
'--user' is used when you do not have permission to install packages in the root dir, remove it won't raise errors.

**Comment by shui-tian-ju-shi** [comment]
To run ict-eval.py, I think just need to add the ict-eval path  downloaded, right? I did so, but I ran into this problem.
![image](https://user-images.githubusercontent.com/95734189/165068228-31da819a-0fc0-45f4-85ac-b3b76d0bfd5b.png)
and this is my model path
![image](https://user-images.githubusercontent.com/95734189/165068478-da9cc1c8-886b-4680-8d76-487e3e40564b.png)
But I didn't find a place in ict-eval.py to set the dataset path

**Comment by shui-tian-ju-shi** [comment]
对于你们论文中提到的ICT - ref。我的理解是专门用某个名人的数据来训练一个ict,最后得到他的ict-ref。请问我的理解对吗？

**Comment by shui-tian-ju-shi** [comment]
I mean that I can just run ict_ eval.py without preprocess.py.  is it？
