### ISSUE TITLE
身份一致性

### ISSUE THREAD

**Issue by shui-tian-ju-shi** [LightDXY/ICT_DeepFake#4]
请问你们方法提到的身份一致性的身份信息可不可以理解成人脸和背景图片来自两张照片，所以他们有着不同的数据分布呢，然后利用transformer来提取这种差异。

**Comment by LightDXY** [comment]
![image](https://user-images.githubusercontent.com/18134953/165679921-1813ce9e-e5ac-438e-b3cd-1a2e7a59e0c0.png)
![image](https://user-images.githubusercontent.com/18134953/165679973-1b6e3234-e225-483f-b16a-46e36917b345.png)

Of course not, the background does not have identity information, please refer to this section.

**Comment by shui-tian-ju-shi** [comment]
thanks for your reply very much!
