### ISSUE TITLE
I followed the test step, but got bad result

### ISSUE THREAD

**Issue by lulin60** [LightDXY/ICT_DeepFake#6]
Hi ,I followed your step, and test your data, but I dont known why I got so bad result? Could help me?
<img width="660" alt="result" src="https://user-images.githubusercontent.com/52558724/170037681-1738fe35-587c-4c6a-8dc0-e8fc6e8a05c9.png">

**Comment by LightDXY** [comment]
can you provide the full log and test enviroment? I will check what's the problem.

**Comment by lulin60** [comment]
> can you provide the full log and test enviroment? I will check what's the problem.
the test enviroment:torch_version:1.11.0,python=3.7
this is log：
[ICT_BASE_EVAL-20220524_184503.log](https://github.com/LightDXY/ICT_DeepFake/files/8768689/ICT_BASE_EVAL-20220524_184503.log)

**Comment by LightDXY** [comment]
it seems that the loading pretrain model part failed.
The correct output should be:
    ('Backbone ict_base model generated',)
    Load from ./PRETRAIN/ICT_BASE, epoch 29
    Loading: ref.pkl Drop: 0
    Load Ref Finished: torch.Size([1, 2420, 384])

Maybe you should use a single GPU to debug at first, and check the output difference between your output and the log we provided (https://github.com/LightDXY/ICT_DeepFake/releases/download/v0.1.0/ff_eval.log).

Besides, the torch we used is 1.6.0, run the setup.sh to get the right environment.

**Comment by lulin60** [comment]
@LightDXY 
1. Yes, I also  find that problem in the code is the model state_dict not to be loaded,so I added it in the code like this. 
2. But i have another problem: In tab1,I dont know which the hq or lq data in FF++ is used for experiments,could help me? Thank you for your help. 
<img width="730" alt="WechatIMG303" src="https://user-images.githubusercontent.com/52558724/170516365-8d8e9ecd-be0c-49aa-8a96-9e5720206fa8.png">
.

**Comment by lulin60** [comment]
@LightDXY 
1.Yes, I also find that problem in the code is the model state_dict not to be loaded,so I add it in the code line 78 by myself and got good results, because the line 70 " load_path=None".(ict_eval.py)
2.Also I have another problem: In tab1, I dont know which the hq or lq data in FF++ is used for experiments,could help me? Thank you for your help.

**Comment by LightDXY** [comment]
We report the HQ data of FF++ in Table.1. And LQ data performance in fig.5 (last mini figure for video compression)

**Comment by Ankit2527** [comment]
@lulin60 what change did you make in code line 78 to make the code run? Do you mind sharing it here? Thank you for your help!

**Comment by Thiresias** [comment]
> We report the HQ data of FF++ in Table.1. And LQ data performance in fig.5 (last mini figure for video compression)


Hi, I have an additional question regarding the results of FF++. Did you compute the frame-level AUC with 'Face2Face' and 'NeuralTextures'?

Because I managed to get a similar frame-level AUC (~90% as reported in the paper for ICT w/o Ref) by only using 'FaceSwap' and 'Deepfakes' subsets. If I test on the four manipulation subsets, the frame-level AUC drops to 75%.

It is not clear to me by reading the paper if you used the four manipulations subsets or only the faceswap subsets.
Thank you in advance for your help!
